token:
  expiration_time: 200000
  secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyush

login:
  url:
    path: /user/login
