token:
  expiration_time: 200000
  secret: eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeepiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyush

login:
  url:
    path: /user/login
