token:
  expiration_time: 200000
  secret: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyshpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyushpiyush

login:
  url:
    path: /user/login
